[package]
name = "adblock-ebpf"
version = "0.1.0"
license = "Dual MIT/GPL"
edition.workspace = true

[dependencies]
adblock-common = { path = "../adblock-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "adblock"
path = "src/main.rs"
